apiVersion: v1
kind: Service
metadata:
  name: df-pulse-service
  labels:
    app: distributedformer
    component: pulse-network
spec:
  selector:
    app: distributedformer
    component: pulse-network
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: df-redis-service
  labels:
    app: distributedformer
    component: redis
spec:
  selector:
    app: distributedformer
    component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
